name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
build:
	cat main.c calculator.c sinterest.c compound_interest.c >final.c

compile:
        
	gcc final.c -o final.out

run:
	./final.out
