name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

	build:
		cat main.c calculator.c sinterest.c compound_interest.c >final.c

	complie:
        
		gcc final.c -o final.out

	run:
		./final.out
